include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    use_key_in_widget_constructors: true
    avoid_unused_constructor_parameters: true
    prefer_const_constructors: true
    prefer_const_declarations: true
