name: company_finder
description: "Artenix test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.2
  dio: 5.4.1
  get_it: 7.6.7
  flutter_bloc: 8.1.4
  freezed_annotation: 2.4.1
  freezed: 2.4.7
  injectable: 2.3.2
  intl: 0.18.1
  json_annotation: 4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.8
  flutter_lints: 2.0.0
  injectable_generator: 2.4.1
  intl_utils: 2.8.4
  json_serializable: 6.7.1

flutter_intl:
  enabled: true
  main_locale: ru

flutter:
  uses-material-design: true
